language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "eraop"
  - git config user.email "493214262@qq.com"
  - git clone --branch eraop-pages https://${eraop_rep} dist
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${For_CI_Token}@${eraop_rep}" eraop-pages:eraop-pages

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - eraop_rep: github.com/eraop/eraop.git
